server:
  port: 80 # 포트 번호
  servlet: 
    encoding:
      charset: utf-8 
      force: true
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: false
      
spring: 
  mail:
    host: smtp.naver.com
    port: 465
    username: ekdns8276@naver.com
    password: ekqls2113!
    properties:
       mail:
        smtp:
          starttls:
            enable: true
#            required: true
          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
          ssl:
            #trust: smtp.naver.com
            enable: true
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
    view: # JSP 사용 설정
      prefix: /WEB-INF/view/ # jsp 파일 경로
      suffix: .jsp # 확장자
  servlet:
    multipart:
      max-file-size: 20MB #최대 20MB()
  datasource: # DB 설정
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: user # 유저 이름
    password: # 비밀번호 (비워두면 비밀번호 X)
  sql: 
    init: # 초기 sql 파일 읽기 
      schema-locations: # 스키마 (테이블 생성 등)
      - classpath:db/table.sql # 콜론 띄어쓰기 X, db 폴더 아래 table.sql 파일 읽으라는 뜻
      data-locations: # 샘플 데이터
      - classpath:db/data.sql
  h2: # H2 Database 설정
    console: 
      enabled: true
  output: 
    ansi: # 쿼리문 표준
      enabled: always
 
mybatis:
  mapper-locations:         # **.xml : 해당 경로 아래 모든 xml 파일
  - classpath:mapper/**.xml # classpath는 src/main/resources/ 아래부터 시작
  configuration:
    map-underscore-to-camel-case: true